#!/usr/bin/env bash
# Nginx error 404 page
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page \n" > /var/www/html/error.html
sudo sed -i '/server.name..;/a \        error_page 404 /error.html;\n   location = /error.html {\n              root /var/www/html;\n           internal;\n     }'  /etc/nginx/sites-enabled/default
sudo service nginx restart
