#!/usr/bin/env bash
# Bash script that install and configure HAproxy

sudo apt-get -y update
sudo apt-get -y install haproxy

str_haproxy="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 924-web-01 34.74.113.207:80 check\n\tserver 924-web-02 35.227.64.73:80 check"
echo -e "$str_haproxy" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
